name: build

on:
  push:
    branches: [ main, noetic-devel ] #  when main or noetic-devel branch is pushed to
  pull_request:
    branches: [ main ] # when there is a pull request against main

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
